#!/bin/bash

BINDIR=$(cd "$(dirname "$0")"; pwd)

#LIBS=~/.p2/pool/plugins
LIBS=/Applications/EclipseOxygen1aModeling_iObserve/EclipseModelingTools.app/Contents/Eclipse/plugins

LIST=`cat << EOF
de.uka.ipd.sdq.identifier
org.palladiosimulator.pcm
org.palladiosimulator.pcm.cloud
org.palladiosimulator.pcm.privacy
org.palladiosimulator.pcm.resources
org.palladiosimulator.solver
org.palladiosimulator.solver.context
org.palladiosimulator.analyzer.workflow
org.palladiosimulator.analyzer.completions
org.palladiosimulator.analyzer.resultdecorator
org.palladiosimulator.analyzer.quality
de.uka.ipd.sdq.units
de.uka.ipd.sdq.statistics
de.uka.ipd.sdq.pcm.stochasticexpressions
de.uka.ipd.sdq.featuremodel
de.uka.ipd.sdq.errorhandling
de.uka.ipd.sdq.tcfmoop
de.uka.ipd.sdq.stoex
de.uka.ipd.sdq.stoex.analyser
de.uka.ipd.sdq.probfunction
de.uka.ipd.sdq.probfunction.math
de.uka.ipd.sdq.featuremodel
de.uka.ipd.sdq.dsexplore.qml
de.uka.ipd.sdq.pcm.cost
de.uka.ipd.sdq.pcm.designdecision
de.uka.ipd.sdq.statistics
de.uka.ipd.sdq.pcm.stochasticexpressions
de.uka.ipd.sdq.workflow.mdsd
de.uka.ipd.sdq.workflow.launchconfig
de.uka.ipd.sdq.workflow.logging.console
de.uka.ipd.sdq.workflow.ui
de.uka.ipd.sdq.workflow
org.opt4j
protocom.extension
org.eclipse.emf.ecore
org.eclipse.emf.cdo
org.eclipse.emf.cdo.common
org.eclipse.ocl
org.eclipse.ocl.common
org.eclipse.ocl.ecore
org.eclipse.net4j
org.eclipse.net4j.util
org.eclipse.equinox.common
org.eclipse.xpand
org.eclipse.xtend.core
org.eclipse.xtend.typesystem.emf
org.eclipse.xtend.standalone
org.eclipse.xtend
org.eclipse.lib
org.eclipse.lib.macro
lpg.runtime.java

# PerOpteryx runtime deps
ch.ethz.iks.r_osgi.remote
com.google.guava
com.google.inject
com.ibm.icu
de.mdelab.sdm.interpreter.core
de.mdelab.sdm.interpreter.core.eclipse
de.uka.ipd.sdq.codegen.simucontroller
de.uka.ipd.sdq.codegen.simudatavisualisation.datatypes
de.uka.ipd.sdq.dialogs
de.uka.ipd.sdq.dsexplore
de.uka.ipd.sdq.dsexplore.analysis.cost
de.uka.ipd.sdq.dsexplore.analysis.lqn
de.uka.ipd.sdq.dsexplore.analysis.reliability
de.uka.ipd.sdq.dsexplore.analysis.simucom
de.uka.ipd.sdq.dsexplore.bayesnets
de.uka.ipd.sdq.dsexplore.qml
de.uka.ipd.sdq.dsexplore.qml.handling
de.uka.ipd.sdq.errorhandling
de.uka.ipd.sdq.featureconfig
de.uka.ipd.sdq.featureconfig.edit
de.uka.ipd.sdq.featureinstance.editor
de.uka.ipd.sdq.featuremodel
de.uka.ipd.sdq.featuremodel.edit
de.uka.ipd.sdq.identifier
de.uka.ipd.sdq.identifier.edit
de.uka.ipd.sdq.pcm.codegen.m2m
de.uka.ipd.sdq.pcm.codegen.simucom
de.uka.ipd.sdq.pcm.cost
de.uka.ipd.sdq.pcm.designdecision
de.uka.ipd.sdq.pcm.stochasticexpressions
de.uka.ipd.sdq.probfunction
de.uka.ipd.sdq.probfunction.edit
de.uka.ipd.sdq.probfunction.math
de.uka.ipd.sdq.scheduler
de.uka.ipd.sdq.sensorframework
de.uka.ipd.sdq.sensorframework.adapter
de.uka.ipd.sdq.sensorframework.dialogs
de.uka.ipd.sdq.sensorframework.storage
de.uka.ipd.sdq.simucomframework
de.uka.ipd.sdq.simucomframework.simucomstatus
de.uka.ipd.sdq.simucomframework.simulationdock
de.uka.ipd.sdq.simucomframework.variables
de.uka.ipd.sdq.simulation
de.uka.ipd.sdq.simulation.abstractsimengine
de.uka.ipd.sdq.statistics
de.uka.ipd.sdq.stoex
de.uka.ipd.sdq.stoex.analyser
de.uka.ipd.sdq.stoex.edit
de.uka.ipd.sdq.tcfmoop
de.uka.ipd.sdq.units
de.uka.ipd.sdq.units.edit
de.uka.ipd.sdq.workflow
de.uka.ipd.sdq.workflow.launchconfig
de.uka.ipd.sdq.workflow.logging.console
de.uka.ipd.sdq.workflow.mdsd
de.uka.ipd.sdq.workflow.ui
de.uka.ipd.sdq.workflow.workbench
javax.annotation
javax.inject
javax.servlet
javax.xml
lpg.runtime.java
org.antlr.runtime
org.apache.ant
org.apache.batik.css
org.apache.batik.dom
org.apache.batik.ext.awt
org.apache.batik.svggen
org.apache.batik.util
org.apache.batik.util.gui
org.apache.batik.xml
org.apache.commons.cli
org.apache.commons.codec
org.apache.commons.collections15
org.apache.commons.jxpath
org.apache.commons.lang
org.apache.commons.logging
org.apache.commons.logging.fragment
org.apache.commons.math
org.apache.felix.gogo.command
org.apache.felix.gogo.runtime
org.apache.felix.gogo.shell
org.apache.felix.scr
org.apache.log4j
org.apache.lucene.core
org.eclipse.ant.core
org.eclipse.ant.launching
org.eclipse.ant.ui
org.eclipse.compare
org.eclipse.compare.core
org.eclipse.core.commands
org.eclipse.core.contenttype
org.eclipse.core.databinding
org.eclipse.core.databinding.beans
org.eclipse.core.databinding.observable
org.eclipse.core.databinding.property
org.eclipse.core.expressions
org.eclipse.core.externaltools
org.eclipse.core.filebuffers
org.eclipse.core.filesystem
org.eclipse.core.filesystem.macosx
org.eclipse.core.jobs
org.eclipse.core.net
org.eclipse.core.resources
org.eclipse.core.runtime
org.eclipse.core.variables
org.eclipse.debug.core
org.eclipse.debug.ui
org.eclipse.draw2d
org.eclipse.e4.core.commands
org.eclipse.e4.core.contexts
org.eclipse.e4.core.di
org.eclipse.e4.core.di.annotations
org.eclipse.e4.core.di.extensions
org.eclipse.e4.core.di.extensions.supplier
org.eclipse.e4.core.services
org.eclipse.e4.emf.xpath
org.eclipse.e4.ui.bindings
org.eclipse.e4.ui.css.core
org.eclipse.e4.ui.css.swt
org.eclipse.e4.ui.css.swt.theme
org.eclipse.e4.ui.di
org.eclipse.e4.ui.model.workbench
org.eclipse.e4.ui.services
org.eclipse.e4.ui.widgets
org.eclipse.e4.ui.workbench
org.eclipse.e4.ui.workbench.addons.swt
org.eclipse.e4.ui.workbench.renderers.swt
org.eclipse.e4.ui.workbench.renderers.swt.cocoa
org.eclipse.e4.ui.workbench.swt
org.eclipse.e4.ui.workbench3
org.eclipse.emf
org.eclipse.emf.ant
org.eclipse.emf.cdo
org.eclipse.emf.cdo.common
org.eclipse.emf.codegen
org.eclipse.emf.codegen.ecore
org.eclipse.emf.codegen.ecore.ui
org.eclipse.emf.common
org.eclipse.emf.common.ui
org.eclipse.emf.converter
org.eclipse.emf.databinding
org.eclipse.emf.databinding.edit
org.eclipse.emf.ecore
org.eclipse.emf.ecore.change
org.eclipse.emf.ecore.edit
org.eclipse.emf.ecore.editor
org.eclipse.emf.ecore.xmi
org.eclipse.emf.edit
org.eclipse.emf.edit.ui
org.eclipse.emf.importer
org.eclipse.emf.mapping.ecore2xml
org.eclipse.emf.mwe.core
org.eclipse.emf.mwe.utils
org.eclipse.emf.mwe2.lib
org.eclipse.emf.mwe2.runtime
org.eclipse.emf.query
org.eclipse.emf.query.ocl
org.eclipse.emf.transaction
org.eclipse.emf.validation
org.eclipse.emf.workspace
org.eclipse.equinox.app
org.eclipse.equinox.bidi
org.eclipse.equinox.common
org.eclipse.equinox.console
org.eclipse.equinox.ds
org.eclipse.equinox.event
org.eclipse.equinox.frameworkadmin
org.eclipse.equinox.frameworkadmin.equinox
org.eclipse.equinox.http.jetty
org.eclipse.equinox.http.servlet
org.eclipse.equinox.p2.artifact.repository
org.eclipse.equinox.p2.core
org.eclipse.equinox.p2.director
org.eclipse.equinox.p2.director.app
org.eclipse.equinox.p2.engine
org.eclipse.equinox.p2.garbagecollector
org.eclipse.equinox.p2.jarprocessor
org.eclipse.equinox.p2.metadata
org.eclipse.equinox.p2.metadata.repository
org.eclipse.equinox.p2.operations
org.eclipse.equinox.p2.publisher
org.eclipse.equinox.p2.publisher.eclipse
org.eclipse.equinox.p2.repository
org.eclipse.equinox.p2.repository.tools
org.eclipse.equinox.p2.touchpoint.eclipse
org.eclipse.equinox.p2.ui
org.eclipse.equinox.p2.updatesite
org.eclipse.equinox.preferences
org.eclipse.equinox.registry
org.eclipse.equinox.security
org.eclipse.equinox.security.macosx
org.eclipse.equinox.security.ui
org.eclipse.equinox.simpleconfigurator
org.eclipse.equinox.simpleconfigurator.manipulator
org.eclipse.equinox.util
org.eclipse.gef
org.eclipse.gmf.runtime.common.core
org.eclipse.gmf.runtime.common.ui
org.eclipse.gmf.runtime.common.ui.action
org.eclipse.gmf.runtime.common.ui.services
org.eclipse.gmf.runtime.common.ui.services.action
org.eclipse.gmf.runtime.diagram.core
org.eclipse.gmf.runtime.diagram.ui
org.eclipse.gmf.runtime.draw2d.ui
org.eclipse.gmf.runtime.draw2d.ui.render
org.eclipse.gmf.runtime.emf.clipboard.core
org.eclipse.gmf.runtime.emf.commands.core
org.eclipse.gmf.runtime.emf.core
org.eclipse.gmf.runtime.emf.type.core
org.eclipse.gmf.runtime.emf.ui
org.eclipse.gmf.runtime.gef.ui
org.eclipse.gmf.runtime.notation
org.eclipse.help
org.eclipse.help.base
org.eclipse.help.ui
org.eclipse.jdt
org.eclipse.jdt.compiler.apt
org.eclipse.jdt.compiler.tool
org.eclipse.jdt.core
org.eclipse.jdt.core.manipulation
org.eclipse.jdt.debug
org.eclipse.jdt.debug.ui
org.eclipse.jdt.junit
org.eclipse.jdt.junit.core
org.eclipse.jdt.junit.runtime
org.eclipse.jdt.launching
org.eclipse.jdt.ui
org.eclipse.jetty.http
org.eclipse.jetty.io
org.eclipse.jetty.security
org.eclipse.jetty.server
org.eclipse.jetty.servlet
org.eclipse.jetty.util
org.eclipse.jface
org.eclipse.jface.databinding
org.eclipse.jface.text
org.eclipse.ltk.core.refactoring
org.eclipse.ltk.ui.refactoring
org.eclipse.m2m.qvt.oml
org.eclipse.m2m.qvt.oml.common
org.eclipse.m2m.qvt.oml.cst.parser
org.eclipse.m2m.qvt.oml.ecore.imperativeocl
org.eclipse.m2m.qvt.oml.emf.util
org.eclipse.m2m.qvt.oml.ocl
org.eclipse.m2m.qvt.oml.project
org.eclipse.m2m.qvt.oml.runtime
org.eclipse.net4j
org.eclipse.net4j.util
org.eclipse.ocl
org.eclipse.ocl.common
org.eclipse.ocl.ecore
org.eclipse.osgi
org.eclipse.osgi.compatibility.state
org.eclipse.osgi.services
org.eclipse.osgi.util
org.eclipse.pde.build
org.eclipse.pde.core
org.eclipse.pde.launching
org.eclipse.pde.ui
org.eclipse.search
org.eclipse.sirius
org.eclipse.sirius.common
org.eclipse.sirius.common.ui
org.eclipse.sirius.ecore.extender
org.eclipse.sirius.ext.base
org.eclipse.sirius.ext.e3.ui
org.eclipse.sirius.ext.emf
org.eclipse.sirius.ext.emf.tx
org.eclipse.sirius.ext.emf.ui
org.eclipse.sirius.ext.jface
org.eclipse.sirius.ext.swt
org.eclipse.sirius.ui
org.eclipse.swt
org.eclipse.swt.cocoa.macosx.x86_64
org.eclipse.team.core
org.eclipse.team.ui
org.eclipse.text
org.eclipse.ui
org.eclipse.ui.cheatsheets
org.eclipse.ui.cocoa
org.eclipse.ui.console
org.eclipse.ui.editors
org.eclipse.ui.externaltools
org.eclipse.ui.forms
org.eclipse.ui.ide
org.eclipse.ui.intro
org.eclipse.ui.navigator
org.eclipse.ui.navigator.resources
org.eclipse.ui.trace
org.eclipse.ui.views
org.eclipse.ui.views.log
org.eclipse.ui.views.properties.tabbed
org.eclipse.ui.workbench
org.eclipse.ui.workbench.texteditor
org.eclipse.uml2.codegen.ecore
org.eclipse.uml2.common
org.eclipse.uml2.common.edit
org.eclipse.uml2.types
org.eclipse.uml2.uml
org.eclipse.uml2.uml.ecore.importer
org.eclipse.update.configurator
org.eclipse.wst.common.core
org.eclipse.wst.server.core
org.eclipse.wst.server.discovery
org.eclipse.xpand
org.eclipse.xtend
org.eclipse.xtend.core
org.eclipse.xtend.lib
org.eclipse.xtend.lib.macro
org.eclipse.xtend.standalone
org.eclipse.xtend.typesystem.emf
org.eclipse.xtext
org.eclipse.xtext.builder
org.eclipse.xtext.builder.standalone
org.eclipse.xtext.common.types
org.eclipse.xtext.common.types.edit
org.eclipse.xtext.common.types.ui
org.eclipse.xtext.ecore
org.eclipse.xtext.generator
org.eclipse.xtext.ide
org.eclipse.xtext.junit4
org.eclipse.xtext.logging
org.eclipse.xtext.smap
org.eclipse.xtext.ui
org.eclipse.xtext.ui.codetemplates
org.eclipse.xtext.ui.codetemplates.ui
org.eclipse.xtext.ui.shared
org.eclipse.xtext.ui.testing
org.eclipse.xtext.util
org.eclipse.xtext.xbase
org.eclipse.xtext.xbase.ide
org.eclipse.xtext.xbase.junit
org.eclipse.xtext.xbase.lib
org.eclipse.xtext.xbase.ui
org.eclipse.xtext.xtext.generator
org.hamcrest.core
org.jfree.jfreechart
org.jscience
org.junit
org.modelversioning.emfprofile
org.modelversioning.emfprofile.edit
org.modelversioning.emfprofile.project
org.modelversioning.emfprofile.registry
org.objectweb.asm
org.opt4j
org.palladiosimulator.analyzer.accuracy
org.palladiosimulator.analyzer.completions
org.palladiosimulator.analyzer.quality
org.palladiosimulator.analyzer.resultdecorator
org.palladiosimulator.analyzer.workflow
org.palladiosimulator.commons
org.palladiosimulator.editors.commons.dialogs
org.palladiosimulator.edp2
org.palladiosimulator.edp2.batchexport
org.palladiosimulator.edp2.dao
org.palladiosimulator.edp2.datastream
org.palladiosimulator.edp2.edit
org.palladiosimulator.edp2.repository.local
org.palladiosimulator.edp2.ui
org.palladiosimulator.edp2.util
org.palladiosimulator.edp2.visualization
org.palladiosimulator.edp2.visualization.jfreechart
org.palladiosimulator.mdsdprofiles.api
org.palladiosimulator.measurementframework
org.palladiosimulator.metricspec
org.palladiosimulator.metricspec.edit
org.palladiosimulator.monitorrepository
org.palladiosimulator.pcm
org.palladiosimulator.pcm.edit
org.palladiosimulator.pcm.edp2.measuringpoint
org.palladiosimulator.pcm.resources
org.palladiosimulator.pcm.ui
org.palladiosimulator.probeframework
org.palladiosimulator.recorderframework
org.palladiosimulator.recorderframework.edp2
org.palladiosimulator.recorderframework.sensorframework
org.palladiosimulator.reliability
org.palladiosimulator.reliability.sensitivity
org.palladiosimulator.servicelevelobjective
org.palladiosimulator.servicelevelobjective.edp2
org.palladiosimulator.simulizar
org.palladiosimulator.simulizar.action
org.palladiosimulator.simulizar.action.edit
org.palladiosimulator.simulizar.edp2.measuringpoint
org.palladiosimulator.simulizar.reconfiguration.qvto
org.palladiosimulator.simulizar.reconfiguration.storydiagram
org.palladiosimulator.simulizar.reconfigurationrule
org.palladiosimulator.simulizar.runtimemeasurement
org.palladiosimulator.simulizar.ui
org.palladiosimulator.solver
org.palladiosimulator.solver.context
org.palladiosimulator.solver.lqn
org.palladiosimulator.solver.reliability
org.palladiosimulator.solver.spa
org.palladiosimulator.solver.spa.basicsolver
org.palladiosimulator.solver.spa.resourcemodel
org.sat4j.core
org.sat4j.pb
org.scaledl.usageevolution
org.slf4j.api
org.slf4j.impl.log4j12
org.storydriven.core
org.storydriven.storydiagrams
org.storydriven.storydiagrams.expressions
org.storydriven.storydiagrams.interpreter.core
org.storydriven.storydiagrams.interpreter.eclipse
org.tukaani.xz
org.w3c.css.sac
org.w3c.dom.events
org.w3c.dom.smil
org.w3c.dom.svg
tools.descartes.dlim.generator
EOF`

MVNDIR="${BINDIR}/mvn-repo"

if [ ! -d "${MVNDIR}" ] ; then
	mkdir "${MVNDIR}"
fi

export GRADLE_DEPENDENCIES="${BINDIR}/gradle.dependencies"

NEWLINE=$'\n'

rm -f "${GRADLE_DEPENDENCIES}"
touch "${GRADLE_DEPENDENCIES}"

for I in $LIST ; do
	echo "Op $I"
	for P in `find ${LIBS} -name "${I}_*.jar"` ; do
		echo "$P"
		if [ -f "$P" ] ; then
			N=`basename $P`
			ARTIFACT=`echo $N | sed 's/^\(.*\)_.*$/\1/'`
			VERSION=`echo $N | sed 's/^.*_\(.*\)\.jar$/\1/'`
			echo $N
		#	echo $ARTIFACT
		#	echo $VERSION
			mvn org.apache.maven.plugins:maven-install-plugin:2.3.1:install-file -Dfile="$P" \
				-DgroupId=extra -DartifactId=$ARTIFACT -Dpackaging=jar -Dversion=$VERSION \
				-DlocalRepositoryPath=mvn-repo
			echo "compile 'extra:${ARTIFACT}:${VERSION}'" >> "${GRADLE_DEPENDENCIES}"
		fi
	done
done

# end
